import {platformBrowserDynamic} from "@angular/platform-browser-dynamic";
import {hotModuleReplacement} from "./hot-store";
import "rxjs/add/operator/map";
import "rxjs/add/operator/filter";
import "rxjs/add/operator/share";
import "rxjs/add/operator/take";
import "rxjs/add/operator/mergeMap";
import "rxjs/add/operator/distinctUntilChanged";
import "rxjs/add/operator/retryWhen";
import "rxjs/add/operator/debounceTime";
import "rxjs/operator/finally";
import "rxjs/add/operator/finally";
import "rxjs/add/operator/publishReplay";
import "rxjs/add/operator/do";
import "rxjs/add/operator/switchMap";
import "rxjs/add/observable/combineLatest";
import "rxjs/add/operator/startWith";
import "bootstrap";
import {DevModule} from "./dev.module";
hotModuleReplacement(() => platformBrowserDynamic().bootstrapModule(DevModule), module);
