/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from "@angular/core/src/linker/ng_module_factory";
import * as import1 from "./index";
import * as import2 from "@angular/common/src/common_module";
import * as import3 from "@angular/core/src/application_module";
import * as import4 from "@angular/platform-browser/src/browser";
import * as import5 from "@angular/router/src/router_module";
import * as import6 from "@angular/forms/src/directives";
import * as import7 from "@angular/forms/src/form_providers";
import * as import8 from "@angular/http/src/http_module";
import * as import9 from "../common/index";
import * as import10 from "../about/index";
import * as import11 from "../authentication/index";
import * as import12 from "../stock/index";
import * as import13 from "@angular/common/src/localization";
import * as import14 from "@angular/core/src/application_init";
import * as import15 from "@angular/core/src/testability/testability";
import * as import16 from "@angular/core/src/application_ref";
import * as import17 from "@angular/core/src/linker/compiler";
import * as import18 from "@angular/platform-browser/src/dom/events/hammer_gestures";
import * as import19 from "@angular/platform-browser/src/dom/events/event_manager";
import * as import20 from "@angular/platform-browser/src/dom/shared_styles_host";
import * as import21 from "@angular/platform-browser/src/dom/dom_renderer";
import * as import22 from "@angular/platform-browser/src/security/dom_sanitization_service";
import * as import23 from "@angular/core/src/linker/view_utils";
import * as import24 from "@angular/platform-browser/src/browser/title";
import * as import25 from "@angular/forms/src/directives/radio_control_value_accessor";
import * as import26 from "@angular/forms/src/form_builder";
import * as import27 from "@angular/http/src/backends/browser_xhr";
import * as import28 from "@angular/http/src/base_response_options";
import * as import29 from "@angular/http/src/backends/xhr_backend";
import * as import30 from "@angular/http/src/base_request_options";
import * as import31 from "../common/common.sandbox";
import * as import32 from "@angular/router/src/url_tree";
import * as import33 from "@angular/router/src/router_outlet_map";
import * as import34 from "@angular/common/src/location/location";
import * as import35 from "@angular/core/src/linker/system_js_ng_module_factory_loader";
import * as import36 from "../common/authenticated.guard";
import * as import37 from "../common/realtime";
import * as import38 from "../authentication/services/authentication.service";
import * as import39 from "../authentication/authentication.sandbox";
import * as import40 from "../stock/services/stock.service";
import * as import41 from "../stock/services/wineCom.service";
import * as import42 from "../stock/stock.sandbox";
import * as import43 from "./app.sandbox";
import * as import44 from "@angular/core/src/di/injector";
import * as import45 from "../authentication/containers/authentication/authentication.container.ngfactory";
import * as import46 from "../about/containers/about-page/about-page.container.ngfactory";
import * as import47 from "../stock/containers/stock-page/stock-page.container.ngfactory";
import * as import48 from "../stock/containers/add-stock-page/add-stock-page.container.ngfactory";
import * as import49 from "../stock/containers/edit-stock-page/edit-stock-page.container.ngfactory";
import * as import50 from "@angular/core/src/application_tokens";
import * as import51 from "@angular/platform-browser/src/dom/events/dom_events";
import * as import52 from "@angular/platform-browser/src/dom/events/key_events";
import * as import53 from "@angular/core/src/zone/ng_zone";
import * as import54 from "@angular/platform-browser/src/dom/debug/ng_probe";
import * as import55 from "./customHttp";
import * as import56 from "@ngrx/store/src/store";
import * as import57 from "@angular/common/src/location/platform_location";
import * as import58 from "@angular/common/src/location/location_strategy";
import * as import59 from "../authentication/containers/authentication/authentication.container";
import * as import60 from "../about/containers/about-page/about-page.container";
import * as import61 from "../stock/containers/stock-page/stock-page.container";
import * as import62 from "../stock/containers/add-stock-page/add-stock-page.container";
import * as import63 from "../stock/containers/edit-stock-page/edit-stock-page.container";
import * as import64 from "@angular/router/src/router";
import * as import65 from "@angular/core/src/console";
import * as import66 from "@angular/core/src/i18n/tokens";
import * as import79 from "@angular/core/src/i18n/tokens";
import * as import67 from "@angular/core/src/error_handler";
import * as import68 from "@angular/platform-browser/src/dom/dom_tokens";
import * as import69 from "@angular/platform-browser/src/dom/animation_driver";
import * as import70 from "@angular/core/src/render/api";
import * as import71 from "@angular/core/src/security";
import * as import72 from "@angular/core/src/change_detection/differs/iterable_differs";
import * as import73 from "@angular/core/src/change_detection/differs/keyvalue_differs";
import * as import74 from "@angular/http/src/interfaces";
import * as import75 from "@angular/http/src/http";
import * as import76 from "@angular/core/src/linker/ng_module_factory_loader";
import * as import77 from "@angular/router/src/router_config_loader";
import * as import78 from "@angular/router/src/router_state";
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _ROUTER_FORROOT_GUARD_3:any;
  _RouterModule_4:import5.RouterModule;
  _InternalFormsSharedModule_5:import6.InternalFormsSharedModule;
  _FormsModule_6:import7.FormsModule;
  _ReactiveFormsModule_7:import7.ReactiveFormsModule;
  _HttpModule_8:import8.HttpModule;
  _CommonLogicModule_9:import9.CommonLogicModule;
  _AboutModule_10:import10.AboutModule;
  _AuthenticationModule_11:import11.AuthenticationModule;
  _StockModule_12:import12.StockModule;
  _AppModule_13:import1.AppModule;
  __LOCALE_ID_14:any;
  __NgLocalization_15:import13.NgLocaleLocalization;
  _ErrorHandler_16:any;
  _ApplicationInitStatus_17:import14.ApplicationInitStatus;
  _Testability_18:import15.Testability;
  _ApplicationRef__19:import16.ApplicationRef_;
  __ApplicationRef_20:any;
  __Compiler_21:import17.Compiler;
  __APP_ID_22:any;
  __DOCUMENT_23:any;
  __HAMMER_GESTURE_CONFIG_24:import18.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_25:any[];
  __EventManager_26:import19.EventManager;
  __DomSharedStylesHost_27:import20.DomSharedStylesHost;
  __AnimationDriver_28:any;
  __DomRootRenderer_29:import21.DomRootRenderer_;
  __RootRenderer_30:any;
  __DomSanitizer_31:import22.DomSanitizerImpl;
  __Sanitizer_32:any;
  __ViewUtils_33:import23.ViewUtils;
  __IterableDiffers_34:any;
  __KeyValueDiffers_35:any;
  __SharedStylesHost_36:any;
  __Title_37:import24.Title;
  __RadioControlRegistry_38:import25.RadioControlRegistry;
  __FormBuilder_39:import26.FormBuilder;
  __BrowserXhr_40:import27.BrowserXhr;
  __ResponseOptions_41:import28.BaseResponseOptions;
  __XSRFStrategy_42:any;
  __XHRBackend_43:import29.XHRBackend;
  __RequestOptions_44:import30.BaseRequestOptions;
  __Http_45:any;
  __CommonSandbox_46:import31.CommonSandbox;
  __UrlSerializer_47:import32.DefaultUrlSerializer;
  __RouterOutletMap_48:import33.RouterOutletMap;
  __ROUTER_CONFIGURATION_49:any;
  __LocationStrategy_50:any;
  __Location_51:import34.Location;
  __NgModuleFactoryLoader_52:import35.SystemJsNgModuleLoader;
  __ROUTES_53:any[];
  __Router_54:any;
  __AuthenticatedGuard_55:import36.AuthenticatedGuard;
  __RealTime_56:import37.RealTime;
  __AuthenticationService_57:import38.AuthenticationService;
  __AuthenticationSandbox_58:import39.AuthenticationSandbox;
  __StockService_59:import40.StockService;
  __WineComService_60:import41.WineComService;
  __StockSandbox_61:import42.StockSandbox;
  __ActivatedRoute_62:any;
  __APP_BOOTSTRAP_LISTENER_63:any[];
  __AppSandbox_64:import43.AppSandbox;
  __TRANSLATIONS_FORMAT_65:any;
  constructor(parent:import44.Injector) {
    super(parent,[
      import45.AuthenticationContainerNgFactory,
      import46.AboutPageContainerNgFactory,
      import47.StockPageContainerNgFactory,
      import48.AddStockPageContainerNgFactory,
      import49.EditStockPageContainerNgFactory
    ]
    ,[]);
  }
  get _LOCALE_ID_14():any {
    if ((this.__LOCALE_ID_14 == (null as any))) { (this.__LOCALE_ID_14 = (null as any)); }
    return this.__LOCALE_ID_14;
  }
  get _NgLocalization_15():import13.NgLocaleLocalization {
    if ((this.__NgLocalization_15 == (null as any))) { (this.__NgLocalization_15 = new import13.NgLocaleLocalization(this._LOCALE_ID_14)); }
    return this.__NgLocalization_15;
  }
  get _ApplicationRef_20():any {
    if ((this.__ApplicationRef_20 == (null as any))) { (this.__ApplicationRef_20 = this._ApplicationRef__19); }
    return this.__ApplicationRef_20;
  }
  get _Compiler_21():import17.Compiler {
    if ((this.__Compiler_21 == (null as any))) { (this.__Compiler_21 = new import17.Compiler()); }
    return this.__Compiler_21;
  }
  get _APP_ID_22():any {
    if ((this.__APP_ID_22 == (null as any))) { (this.__APP_ID_22 = import50._appIdRandomProviderFactory()); }
    return this.__APP_ID_22;
  }
  get _DOCUMENT_23():any {
    if ((this.__DOCUMENT_23 == (null as any))) { (this.__DOCUMENT_23 = import4._document()); }
    return this.__DOCUMENT_23;
  }
  get _HAMMER_GESTURE_CONFIG_24():import18.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_24 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_24 = new import18.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_24;
  }
  get _EVENT_MANAGER_PLUGINS_25():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_25 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_25 = [
      new import51.DomEventsPlugin(),
      new import52.KeyEventsPlugin(),
      new import18.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_24)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_25;
  }
  get _EventManager_26():import19.EventManager {
    if ((this.__EventManager_26 == (null as any))) { (this.__EventManager_26 = new import19.EventManager(this._EVENT_MANAGER_PLUGINS_25,this.parent.get(import53.NgZone))); }
    return this.__EventManager_26;
  }
  get _DomSharedStylesHost_27():import20.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_27 == (null as any))) { (this.__DomSharedStylesHost_27 = new import20.DomSharedStylesHost(this._DOCUMENT_23)); }
    return this.__DomSharedStylesHost_27;
  }
  get _AnimationDriver_28():any {
    if ((this.__AnimationDriver_28 == (null as any))) { (this.__AnimationDriver_28 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_28;
  }
  get _DomRootRenderer_29():import21.DomRootRenderer_ {
    if ((this.__DomRootRenderer_29 == (null as any))) { (this.__DomRootRenderer_29 = new import21.DomRootRenderer_(this._DOCUMENT_23,this._EventManager_26,this._DomSharedStylesHost_27,this._AnimationDriver_28)); }
    return this.__DomRootRenderer_29;
  }
  get _RootRenderer_30():any {
    if ((this.__RootRenderer_30 == (null as any))) { (this.__RootRenderer_30 = import54._createConditionalRootRenderer(this._DomRootRenderer_29,this.parent.get(import54.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_30;
  }
  get _DomSanitizer_31():import22.DomSanitizerImpl {
    if ((this.__DomSanitizer_31 == (null as any))) { (this.__DomSanitizer_31 = new import22.DomSanitizerImpl()); }
    return this.__DomSanitizer_31;
  }
  get _Sanitizer_32():any {
    if ((this.__Sanitizer_32 == (null as any))) { (this.__Sanitizer_32 = this._DomSanitizer_31); }
    return this.__Sanitizer_32;
  }
  get _ViewUtils_33():import23.ViewUtils {
    if ((this.__ViewUtils_33 == (null as any))) { (this.__ViewUtils_33 = new import23.ViewUtils(this._RootRenderer_30,this._APP_ID_22,this._Sanitizer_32)); }
    return this.__ViewUtils_33;
  }
  get _IterableDiffers_34():any {
    if ((this.__IterableDiffers_34 == (null as any))) { (this.__IterableDiffers_34 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_34;
  }
  get _KeyValueDiffers_35():any {
    if ((this.__KeyValueDiffers_35 == (null as any))) { (this.__KeyValueDiffers_35 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_35;
  }
  get _SharedStylesHost_36():any {
    if ((this.__SharedStylesHost_36 == (null as any))) { (this.__SharedStylesHost_36 = this._DomSharedStylesHost_27); }
    return this.__SharedStylesHost_36;
  }
  get _Title_37():import24.Title {
    if ((this.__Title_37 == (null as any))) { (this.__Title_37 = new import24.Title()); }
    return this.__Title_37;
  }
  get _RadioControlRegistry_38():import25.RadioControlRegistry {
    if ((this.__RadioControlRegistry_38 == (null as any))) { (this.__RadioControlRegistry_38 = new import25.RadioControlRegistry()); }
    return this.__RadioControlRegistry_38;
  }
  get _FormBuilder_39():import26.FormBuilder {
    if ((this.__FormBuilder_39 == (null as any))) { (this.__FormBuilder_39 = new import26.FormBuilder()); }
    return this.__FormBuilder_39;
  }
  get _BrowserXhr_40():import27.BrowserXhr {
    if ((this.__BrowserXhr_40 == (null as any))) { (this.__BrowserXhr_40 = new import27.BrowserXhr()); }
    return this.__BrowserXhr_40;
  }
  get _ResponseOptions_41():import28.BaseResponseOptions {
    if ((this.__ResponseOptions_41 == (null as any))) { (this.__ResponseOptions_41 = new import28.BaseResponseOptions()); }
    return this.__ResponseOptions_41;
  }
  get _XSRFStrategy_42():any {
    if ((this.__XSRFStrategy_42 == (null as any))) { (this.__XSRFStrategy_42 = import8._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_42;
  }
  get _XHRBackend_43():import29.XHRBackend {
    if ((this.__XHRBackend_43 == (null as any))) { (this.__XHRBackend_43 = new import29.XHRBackend(this._BrowserXhr_40,this._ResponseOptions_41,this._XSRFStrategy_42)); }
    return this.__XHRBackend_43;
  }
  get _RequestOptions_44():import30.BaseRequestOptions {
    if ((this.__RequestOptions_44 == (null as any))) { (this.__RequestOptions_44 = new import30.BaseRequestOptions()); }
    return this.__RequestOptions_44;
  }
  get _Http_45():any {
    if ((this.__Http_45 == (null as any))) { (this.__Http_45 = import55.customHttpFactory(this._XHRBackend_43,this._RequestOptions_44,this.parent.get(import56.Store))); }
    return this.__Http_45;
  }
  get _CommonSandbox_46():import31.CommonSandbox {
    if ((this.__CommonSandbox_46 == (null as any))) { (this.__CommonSandbox_46 = new import31.CommonSandbox(this.parent.get(import56.Store))); }
    return this.__CommonSandbox_46;
  }
  get _UrlSerializer_47():import32.DefaultUrlSerializer {
    if ((this.__UrlSerializer_47 == (null as any))) { (this.__UrlSerializer_47 = new import32.DefaultUrlSerializer()); }
    return this.__UrlSerializer_47;
  }
  get _RouterOutletMap_48():import33.RouterOutletMap {
    if ((this.__RouterOutletMap_48 == (null as any))) { (this.__RouterOutletMap_48 = new import33.RouterOutletMap()); }
    return this.__RouterOutletMap_48;
  }
  get _ROUTER_CONFIGURATION_49():any {
    if ((this.__ROUTER_CONFIGURATION_49 == (null as any))) { (this.__ROUTER_CONFIGURATION_49 = {}); }
    return this.__ROUTER_CONFIGURATION_49;
  }
  get _LocationStrategy_50():any {
    if ((this.__LocationStrategy_50 == (null as any))) { (this.__LocationStrategy_50 = import5.provideLocationStrategy(this.parent.get(import57.PlatformLocation),this.parent.get(import58.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_49)); }
    return this.__LocationStrategy_50;
  }
  get _Location_51():import34.Location {
    if ((this.__Location_51 == (null as any))) { (this.__Location_51 = new import34.Location(this._LocationStrategy_50)); }
    return this.__Location_51;
  }
  get _NgModuleFactoryLoader_52():import35.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_52 == (null as any))) { (this.__NgModuleFactoryLoader_52 = new import35.SystemJsNgModuleLoader(this._Compiler_21,this.parent.get(import35.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_52;
  }
  get _ROUTES_53():any[] {
      if ((this.__ROUTES_53 == (null as any))) { (this.__ROUTES_53 = [[
        {
          path: '',
          redirectTo: '/stock',
          pathMatch: 'full',
          canActivate: [import36.AuthenticatedGuard]
        }
        ,
        {
          path: 'authentication',
          component: import59.AuthenticationContainer
        }
        ,
        {
          path: 'about',
          component: import60.AboutPageContainer,
          canActivate: [import36.AuthenticatedGuard]
        }
        ,
        {
          path: 'stock',
          component: import61.StockPageContainer,
          canActivate: [import36.AuthenticatedGuard]
        }
        ,
        {
          path: 'stock/add',
          component: import62.AddStockPageContainer,
          canActivate: [import36.AuthenticatedGuard]
        }
        ,
        {
          path: 'stock/:id',
          component: import63.EditStockPageContainer,
          canActivate: [import36.AuthenticatedGuard]
        }

      ]
    ]); }
    return this.__ROUTES_53;
  }
  get _Router_54():any {
    if ((this.__Router_54 == (null as any))) { (this.__Router_54 = import5.setupRouter(this._ApplicationRef_20,this._UrlSerializer_47,this._RouterOutletMap_48,this._Location_51,this,this._NgModuleFactoryLoader_52,this._Compiler_21,this._ROUTES_53,this._ROUTER_CONFIGURATION_49)); }
    return this.__Router_54;
  }
  get _AuthenticatedGuard_55():import36.AuthenticatedGuard {
    if ((this.__AuthenticatedGuard_55 == (null as any))) { (this.__AuthenticatedGuard_55 = new import36.AuthenticatedGuard(this._Router_54)); }
    return this.__AuthenticatedGuard_55;
  }
  get _RealTime_56():import37.RealTime {
    if ((this.__RealTime_56 == (null as any))) { (this.__RealTime_56 = new import37.RealTime(this.parent.get(import56.Store))); }
    return this.__RealTime_56;
  }
  get _AuthenticationService_57():import38.AuthenticationService {
    if ((this.__AuthenticationService_57 == (null as any))) { (this.__AuthenticationService_57 = new import38.AuthenticationService(this._Http_45)); }
    return this.__AuthenticationService_57;
  }
  get _AuthenticationSandbox_58():import39.AuthenticationSandbox {
    if ((this.__AuthenticationSandbox_58 == (null as any))) { (this.__AuthenticationSandbox_58 = new import39.AuthenticationSandbox(this._AuthenticationService_57,this.parent.get(import56.Store))); }
    return this.__AuthenticationSandbox_58;
  }
  get _StockService_59():import40.StockService {
    if ((this.__StockService_59 == (null as any))) { (this.__StockService_59 = new import40.StockService(this.parent.get(import56.Store),this._Http_45)); }
    return this.__StockService_59;
  }
  get _WineComService_60():import41.WineComService {
    if ((this.__WineComService_60 == (null as any))) { (this.__WineComService_60 = new import41.WineComService(this._Http_45)); }
    return this.__WineComService_60;
  }
  get _StockSandbox_61():import42.StockSandbox {
    if ((this.__StockSandbox_61 == (null as any))) { (this.__StockSandbox_61 = new import42.StockSandbox(this.parent.get(import56.Store),this._StockService_59,this._WineComService_60)); }
    return this.__StockSandbox_61;
  }
  get _ActivatedRoute_62():any {
    if ((this.__ActivatedRoute_62 == (null as any))) { (this.__ActivatedRoute_62 = import5.rootRoute(this._Router_54)); }
    return this.__ActivatedRoute_62;
  }
  get _APP_BOOTSTRAP_LISTENER_63():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_63 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_63 = [import5.initialRouterNavigation(this._Router_54,this._ROUTER_CONFIGURATION_49)]); }
    return this.__APP_BOOTSTRAP_LISTENER_63;
  }
  get _AppSandbox_64():import43.AppSandbox {
    if ((this.__AppSandbox_64 == (null as any))) { (this.__AppSandbox_64 = new import43.AppSandbox(this.parent.get(import56.Store),this._AuthenticationService_57,this._StockService_59,this._RealTime_56)); }
    return this.__AppSandbox_64;
  }
  get _TRANSLATIONS_FORMAT_65():any {
    if ((this.__TRANSLATIONS_FORMAT_65 == (null as any))) { (this.__TRANSLATIONS_FORMAT_65 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_65;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_3 = import5.provideForRootGuard(this.parent.get(import64.Router,(null as any)));
    this._RouterModule_4 = new import5.RouterModule(this._ROUTER_FORROOT_GUARD_3);
    this._InternalFormsSharedModule_5 = new import6.InternalFormsSharedModule();
    this._FormsModule_6 = new import7.FormsModule();
    this._ReactiveFormsModule_7 = new import7.ReactiveFormsModule();
    this._HttpModule_8 = new import8.HttpModule();
    this._CommonLogicModule_9 = new import9.CommonLogicModule();
    this._AboutModule_10 = new import10.AboutModule();
    this._AuthenticationModule_11 = new import11.AuthenticationModule();
    this._StockModule_12 = new import12.StockModule();
    this._AppModule_13 = new import1.AppModule();
    this._ErrorHandler_16 = import4.errorHandler();
    this._ApplicationInitStatus_17 = new import14.ApplicationInitStatus(this.parent.get(import14.APP_INITIALIZER,(null as any)));
    this._Testability_18 = new import15.Testability(this.parent.get(import53.NgZone));
    this._ApplicationRef__19 = new import16.ApplicationRef_(this.parent.get(import53.NgZone),this.parent.get(import65.Console),this,this._ErrorHandler_16,this,this._ApplicationInitStatus_17,this.parent.get(import15.TestabilityRegistry,(null as any)),this._Testability_18);
    return this._AppModule_13;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_3; }
    if ((token === import5.RouterModule)) { return this._RouterModule_4; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_5; }
    if ((token === import7.FormsModule)) { return this._FormsModule_6; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_7; }
    if ((token === import8.HttpModule)) { return this._HttpModule_8; }
    if ((token === import9.CommonLogicModule)) { return this._CommonLogicModule_9; }
    if ((token === import10.AboutModule)) { return this._AboutModule_10; }
    if ((token === import11.AuthenticationModule)) { return this._AuthenticationModule_11; }
    if ((token === import12.StockModule)) { return this._StockModule_12; }
    if ((token === import1.AppModule)) { return this._AppModule_13; }
    if ((token === import66.LOCALE_ID)) { return this._LOCALE_ID_14; }
    if ((token === import13.NgLocalization)) { return this._NgLocalization_15; }
    if ((token === import67.ErrorHandler)) { return this._ErrorHandler_16; }
    if ((token === import14.ApplicationInitStatus)) { return this._ApplicationInitStatus_17; }
    if ((token === import15.Testability)) { return this._Testability_18; }
    if ((token === import16.ApplicationRef_)) { return this._ApplicationRef__19; }
    if ((token === import16.ApplicationRef)) { return this._ApplicationRef_20; }
    if ((token === import17.Compiler)) { return this._Compiler_21; }
    if ((token === import50.APP_ID)) { return this._APP_ID_22; }
    if ((token === import68.DOCUMENT)) { return this._DOCUMENT_23; }
    if ((token === import18.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_24; }
    if ((token === import19.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_25; }
    if ((token === import19.EventManager)) { return this._EventManager_26; }
    if ((token === import20.DomSharedStylesHost)) { return this._DomSharedStylesHost_27; }
    if ((token === import69.AnimationDriver)) { return this._AnimationDriver_28; }
    if ((token === import21.DomRootRenderer)) { return this._DomRootRenderer_29; }
    if ((token === import70.RootRenderer)) { return this._RootRenderer_30; }
    if ((token === import22.DomSanitizer)) { return this._DomSanitizer_31; }
    if ((token === import71.Sanitizer)) { return this._Sanitizer_32; }
    if ((token === import23.ViewUtils)) { return this._ViewUtils_33; }
    if ((token === import72.IterableDiffers)) { return this._IterableDiffers_34; }
    if ((token === import73.KeyValueDiffers)) { return this._KeyValueDiffers_35; }
    if ((token === import20.SharedStylesHost)) { return this._SharedStylesHost_36; }
    if ((token === import24.Title)) { return this._Title_37; }
    if ((token === import25.RadioControlRegistry)) { return this._RadioControlRegistry_38; }
    if ((token === import26.FormBuilder)) { return this._FormBuilder_39; }
    if ((token === import27.BrowserXhr)) { return this._BrowserXhr_40; }
    if ((token === import28.ResponseOptions)) { return this._ResponseOptions_41; }
    if ((token === import74.XSRFStrategy)) { return this._XSRFStrategy_42; }
    if ((token === import29.XHRBackend)) { return this._XHRBackend_43; }
    if ((token === import30.RequestOptions)) { return this._RequestOptions_44; }
    if ((token === import75.Http)) { return this._Http_45; }
    if ((token === import31.CommonSandbox)) { return this._CommonSandbox_46; }
    if ((token === import32.UrlSerializer)) { return this._UrlSerializer_47; }
    if ((token === import33.RouterOutletMap)) { return this._RouterOutletMap_48; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_49; }
    if ((token === import58.LocationStrategy)) { return this._LocationStrategy_50; }
    if ((token === import34.Location)) { return this._Location_51; }
    if ((token === import76.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_52; }
    if ((token === import77.ROUTES)) { return this._ROUTES_53; }
    if ((token === import64.Router)) { return this._Router_54; }
    if ((token === import36.AuthenticatedGuard)) { return this._AuthenticatedGuard_55; }
    if ((token === import37.RealTime)) { return this._RealTime_56; }
    if ((token === import38.AuthenticationService)) { return this._AuthenticationService_57; }
    if ((token === import39.AuthenticationSandbox)) { return this._AuthenticationSandbox_58; }
    if ((token === import40.StockService)) { return this._StockService_59; }
    if ((token === import41.WineComService)) { return this._WineComService_60; }
    if ((token === import42.StockSandbox)) { return this._StockSandbox_61; }
    if ((token === import78.ActivatedRoute)) { return this._ActivatedRoute_62; }
    if ((token === import50.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_63; }
    if ((token === import43.AppSandbox)) { return this._AppSandbox_64; }
    if ((token === import79.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_65; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__19.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);